/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.yahtzee_networkproject;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author USER
 */
public class End_page extends javax.swing.JFrame {

    /**
     * Creates new form End_page
     */
    public End_page(String result) {
        initComponents();
        String[] parts = result.split("\\|");
        lab_result.setText(parts[0]);        // اسم الفائز
        lab_scores.setText(parts[1]);        // نتيجة لاعب 1
        
        ImageIcon iconn = new ImageIcon(getClass().getResource("/images/end.png"));
        Image imgee = iconn.getImage().getScaledInstance(
                jLabel1.getWidth(),
                jLabel1.getHeight(),
                Image.SCALE_SMOOTH
        );
        jLabel1.setIcon(new ImageIcon(imgee));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lab_result = new javax.swing.JLabel();
        but_exit = new javax.swing.JButton();
        but_play = new javax.swing.JButton();
        lab_scores = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lab_result.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        lab_result.setForeground(new java.awt.Color(255, 255, 255));
        lab_result.setText("Winner");
        jPanel2.add(lab_result, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        but_exit.setBackground(new java.awt.Color(202, 190, 255));
        but_exit.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        but_exit.setForeground(new java.awt.Color(98, 108, 218));
        but_exit.setText("Exit");
        but_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_exitActionPerformed(evt);
            }
        });
        jPanel2.add(but_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 140, 50));

        but_play.setBackground(new java.awt.Color(202, 190, 255));
        but_play.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        but_play.setForeground(new java.awt.Color(98, 108, 218));
        but_play.setText("Play again");
        but_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_playActionPerformed(evt);
            }
        });
        jPanel2.add(but_play, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 140, 50));

        lab_scores.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        lab_scores.setForeground(new java.awt.Color(153, 0, 0));
        lab_scores.setText("scores");
        jPanel2.add(lab_scores, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 260, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/end.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void but_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_exitActionPerformed
        // TODO add your handling code here:
         System.exit(0);
        
    }//GEN-LAST:event_but_exitActionPerformed

    private void but_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_playActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LogIn().setVisible(true);
    }//GEN-LAST:event_but_playActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(End_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(End_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(End_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(End_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_exit;
    private javax.swing.JButton but_play;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lab_result;
    private javax.swing.JLabel lab_scores;
    // End of variables declaration//GEN-END:variables
}
