/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.yahtzee_networkproject;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class GameScreen extends javax.swing.JFrame {
    GameLogic game = new GameLogic();
    //if i create it in constructor roll_btn can not reach 
    JButton[]buttons;
    //hold selected buttons 
    public void selectedButtons() {
        for (int i = 0; i < buttons.length; i++) {
            // game.dice.held[i] gave error because (الاي بتتغير كل شويه وهو عايز حاجه ثابته فا خزنتها)
            int index = i;
            //once button clicked:
            buttons[i].addActionListener(e -> {
                boolean hold =  game.dice.held[index];
                if(hold==true){
                   hold=false;
                   buttons[index].setBackground(null);
                }else if(hold==false){
                    hold=true;
                        buttons[index].setBackground(Color.blue);
                }
                game.dice.held[index]=hold; 
            });
        }
    }
    
    /**
     * Creates new form GameScreen
     */
    public GameScreen() {
        initComponents();
       buttons=new JButton[]{btn_dice1,btn_dice2,btn_dice3,btn_dice4,btn_dice5};
       selectedButtons();
       DefaultTableModel tableModel = (DefaultTableModel)score_table.getModel();//take a copy from my table
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_dice1 = new javax.swing.JButton();
        btn_dice2 = new javax.swing.JButton();
        btn_dice3 = new javax.swing.JButton();
        btn_dice4 = new javax.swing.JButton();
        btn_dice5 = new javax.swing.JButton();
        btn_roll = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        score_table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        btn_dice1.setText("Dice 1");
        btn_dice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dice1ActionPerformed(evt);
            }
        });

        btn_dice2.setText("Dice 2");
        btn_dice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dice2ActionPerformed(evt);
            }
        });

        btn_dice3.setText("Dice 3");
        btn_dice3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dice3ActionPerformed(evt);
            }
        });

        btn_dice4.setText("Dice 4");
        btn_dice4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dice4ActionPerformed(evt);
            }
        });

        btn_dice5.setText("Dice 5");
        btn_dice5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dice5ActionPerformed(evt);
            }
        });

        btn_roll.setText("Roll Dice");
        btn_roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rollActionPerformed(evt);
            }
        });

        score_table.setBackground(new java.awt.Color(0, 0, 51));
        score_table.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        score_table.setForeground(new java.awt.Color(255, 255, 255));
        score_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Ones", null, null},
                {"Twos", null, null},
                {"Threes", null, null},
                {"Fours", null, null},
                {"Fives", null, null},
                {"Sixes", null, null},
                {"Sum", null, null},
                {"Bonus", null, null},
                {"Three of a kind", null, null},
                {"Four of a kind", null, null},
                {"Full house", null, null},
                {"Small straight", null, null},
                {"Large straight", null, null},
                {"Chance", null, null},
                {"Yahtzee", null, null},
                {null, null, null}
            },
            new String [] {
                "Rolls", "Player1", "Player2"
            }
        ));
        score_table.setToolTipText("");
        score_table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        score_table.setGridColor(new java.awt.Color(255, 255, 255));
        score_table.setName(""); // NOI18N
        score_table.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(score_table);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_roll, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_dice1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_dice2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_dice3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_dice4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_dice5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_dice1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_dice3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_dice2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_dice4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_dice5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btn_roll, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dice1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dice1ActionPerformed

    private void btn_dice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dice2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dice2ActionPerformed

    private void btn_dice3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dice3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dice3ActionPerformed

    private void btn_dice4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dice4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dice4ActionPerformed

    private void btn_dice5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dice5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dice5ActionPerformed

    private void btn_rollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rollActionPerformed
        //System.out.println(getClass().getClassLoader().getResource("/images/1.png"));
        game.rollCount();
        for (int i = 0; i <buttons.length ; i++) {
            //game.dice=  return object but we want arraylist then .dices
            //choose frrom 1-6 store in DiceNum
            int DiceNum=game.dice.dices[i];
            //bring the photo based on DiceNum
            //ImageIcon icon = new ImageIcon(getClass().getResource("/images/" + DiceNum + ".png"));
            //set the photo in their spicific dice 
            //buttons[i].setIcon(icon);
            buttons[i].setText(""+DiceNum);//because it is accept string only
            //close the button after 5th try
            if(game.rollcounter==5){
            btn_roll.setEnabled(false);
            }
        }
        //when all dices seleced client can't press roll button again
        boolean allHeld=true;
        for (int i = 0; i < game.dice.held.length; i++) {
            if(game.dice.held[i]==false){
                allHeld=false;
            }
        }
        if(allHeld==true){
            btn_roll.setEnabled(false);
        }
    }//GEN-LAST:event_btn_rollActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dice1;
    private javax.swing.JButton btn_dice2;
    private javax.swing.JButton btn_dice3;
    private javax.swing.JButton btn_dice4;
    private javax.swing.JButton btn_dice5;
    private javax.swing.JButton btn_roll;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable score_table;
    // End of variables declaration//GEN-END:variables
}
