/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.yahtzee_networkproject;

import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author USER
 */
public class GameScreen extends javax.swing.JFrame {
    GameLogic game = new GameLogic();
    //if i create it in constructor roll_btn can not reach 
    JButton[]buttons;
    /**
     * Creates new form GameScreen
     */
    public GameScreen() {
        initComponents();
       buttons=new JButton[]{btn_dice1,btn_dice2,btn_dice3,btn_dice4,btn_dice5};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_dice1 = new javax.swing.JButton();
        btn_dice2 = new javax.swing.JButton();
        btn_dice3 = new javax.swing.JButton();
        btn_dice4 = new javax.swing.JButton();
        btn_dice5 = new javax.swing.JButton();
        btn_roll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        btn_dice1.setText("Dice 1");
        btn_dice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dice1ActionPerformed(evt);
            }
        });

        btn_dice2.setText("Dice 2");
        btn_dice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dice2ActionPerformed(evt);
            }
        });

        btn_dice3.setText("Dice 3");
        btn_dice3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dice3ActionPerformed(evt);
            }
        });

        btn_dice4.setText("Dice 4");
        btn_dice4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dice4ActionPerformed(evt);
            }
        });

        btn_dice5.setText("Dice 5");
        btn_dice5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dice5ActionPerformed(evt);
            }
        });

        btn_roll.setText("Roll Dice");
        btn_roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rollActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_roll, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_dice1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btn_dice2)
                        .addGap(18, 18, 18)
                        .addComponent(btn_dice3)
                        .addGap(18, 18, 18)
                        .addComponent(btn_dice4)
                        .addGap(18, 18, 18)
                        .addComponent(btn_dice5)))
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(302, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_dice1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_dice2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_dice3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_dice4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_dice5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_roll, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dice1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dice1ActionPerformed

    private void btn_dice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dice2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dice2ActionPerformed

    private void btn_dice3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dice3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dice3ActionPerformed

    private void btn_dice4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dice4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dice4ActionPerformed

    private void btn_dice5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dice5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dice5ActionPerformed

    private void btn_rollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rollActionPerformed
        //System.out.println(getClass().getClassLoader().getResource("/images/1.png"));
        game.rollCount();
        for (int i = 0; i <buttons.length ; i++) {
            //game.dice=  return object but we want arraylist then .dices
            //choose frrom 1-6 store in DiceNum
            int DiceNum=game.dice.dices[i];
            //bring the photo based on DiceNum
            //ImageIcon icon = new ImageIcon(getClass().getResource("/images/" + DiceNum + ".png"));
            //set the photo in their spicific dice 
            //buttons[i].setIcon(icon);
            buttons[i].setText(""+DiceNum);//because it is accept string only
            //close the button after 5th try
            if(game.rollcounter==5){
            btn_roll.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btn_rollActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dice1;
    private javax.swing.JButton btn_dice2;
    private javax.swing.JButton btn_dice3;
    private javax.swing.JButton btn_dice4;
    private javax.swing.JButton btn_dice5;
    private javax.swing.JButton btn_roll;
    // End of variables declaration//GEN-END:variables
}
